// DH-0228: one-shot rasterizer for docs/media/social-preview.svg -> social-preview.png.
//
// Not part of any gate (no `.test.` suffix, not under e2e/ or src/) — this is a static
// documentation asset on the same footing as logo.svg, regenerated by hand only when the
// brand changes. Uses headless Chromium (via the repo's existing playwright dependency and
// e2e/support/chromium.ts resolver, the same pattern e2e/spikes/web/hero-screenshot.ts uses)
// rather than a local rasterizer, specifically to avoid font-substitution risk: Chromium
// ships web-safe Helvetica/Arial-class fonts wherever it runs, so the wordmark renders as the
// intended grotesque sans instead of a serif fallback.
//
// Run:  bun docs/media/social-preview.render.ts

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { chromium } from "playwright";
import { resolveChromiumExecutable } from "../../e2e/support/chromium.ts";

const MEDIA_DIR = resolve(import.meta.dir);
const SVG_PATH = resolve(MEDIA_DIR, "social-preview.svg");
const PNG_PATH = resolve(MEDIA_DIR, "social-preview.png");

const svg = readFileSync(SVG_PATH, "utf8");
const html = `<!doctype html><html><head><style>
  html,body{margin:0;padding:0;width:1280px;height:640px;background:#0b0d12;}
  svg{display:block;}
</style></head><body>${svg}</body></html>`;

const executablePath = await resolveChromiumExecutable();
const browser = await chromium.launch({ executablePath });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 640 } });
  await page.setContent(html, { waitUntil: "load" });
  const png = await page.screenshot({
    type: "png",
    clip: { x: 0, y: 0, width: 1280, height: 640 },
  });
  writeFileSync(PNG_PATH, png);
  console.log(`Wrote ${PNG_PATH} (${png.length} bytes)`);
} finally {
  await browser.close();
}
